### ISSUE TITLE
Does this module work on the USG?

### ISSUE THREAD

**Issue by Ramblurr** [Lochnair/vyatta-wireguard#21]
Is this module confirmed working on the USG?

I'm in the process of deciding between the USG and ER, and the ability to run a wireguard client will be a big decider. Sorry for making an issue about this, wasn't sure where to ask.

Edit: And a follow up question: if the provided binaries won't work, has anyone simply compiled the module and user space tools for the USG?

**Comment by Lochnair** [comment]
As long as you're running the latest firmware for the USG it should most likely work. The downside on the USG is that doing advanced configuration that's not exposed in the controller is a bit of a pain.

**Comment by cinghialino** [comment]
which version should work with the USG?

**Comment by Lochnair** [comment]
@cinghialino The USG should work with the E100 release. The USG-Pro should work with the E200 one.

**Comment by cinghialino** [comment]
@Lochnair thank you. Will try!

**Comment by cinghialino** [comment]
FYI, the E100 release is working on the Ubiquiti USG. I have firmware 4.4.18.5052168 on it.

I had a little bit of difficulties because I'm not used to this, but the connection is on and working.
I wish there would be more commenting between the documentation, just to make people like me more aware of the process. And also some notes on how to deactivate/delete the links.

**thank you.**
