### ISSUE TITLE
Not possible to assign IPv6 address to wg0 interface

### ISSUE THREAD

**Issue by dremon** [Lochnair/vyatta-wireguard#38]
I tried to set IPv6 address (`set interface wireguard wg0 address h:h:h:h::h/64`) but it's not actually assigned to the interface after committing and then it's not possible to delete it, there is an error triggered.

According to the vyatta scripts the `ip addr` command is used unconditionally in the wireguard node for all addresses but I think for ipv6 addressing it must be `ip -6 addr`

**Comment by tssva** [comment]
In most cases `ip -6 addr` is not needed. `ip addr` will detect the type of address being assigned and act accordingly. The issue is that IPv6 addresses unlike IPv4 addresses are lost when a link is brought down as the wireguard interface is briefly during a commit. 

PR #39 applies a priority to the address configuration to make sure the addresses are applied after the interface has come back up.

**Comment by dremon** [comment]
Thanks for quick reply!
