### ISSUE TITLE
Build again for UniFi Security Gateway

### ISSUE THREAD

**Issue by sentrify** [Lochnair/vyatta-wireguard#47]
Recent builds won't work on UniFi Security Gateway.
Latest release that works is `0.0.20180218-1` using `e100` as platform.

Version in controller `4.4.18.5052168`

`uname -a`
`Linux XXX 3.10.20-UBNT #1 SMP Fri Nov 3 15:45:37 MDT 2017 mips64 GNU/Linux`

`MOTD`
```
Linux XXX 3.10.20-UBNT #1 SMP Fri Nov 3 15:45:37 MDT 2017 mips64

  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2017
 |   |  |   |  \  ||  \   |  |   Ubiquiti Networks, Inc.
 |______|___|  /__||__/   |__|
            |_/                  http://www.ubnt.com

      Welcome to EdgeOS on UniFi Security Gateway!
```

`/proc/cpuinfo`
```
system type		: UBNT_E120
machine			: Unknown
processor		: 0
cpu model		: Cavium Octeon+ V0.1
BogoMIPS		: 1000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 64
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented	:
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 1
cpu model		: Cavium Octeon+ V0.1
BogoMIPS		: 1000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 64
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented	:
shadow register sets	: 1
kscratch registers	: 0
core			: 1
VCED exceptions		: not available
VCEI exceptions		: not available
```

**Comment by dcava** [comment]
I've built for the USG firmware 4.4.18.5052168. It is a different kernel version to the most recent e100 build here (3.10.107 vs 3.10.20)

because I'm lazy, I just install the latest built e100.deb from @Lochnair, then copied my wireguard.ko and wg to the right places (to take advantage of the vyatta scripts)

I've forked this repo and changed just the two binary files in the e100 branch - so you can download them from there
https://github.com/dcava/vyatta-wireguard

and do the same if you wish.

If I can get my act together I can try and contribute them back to @Lochnair , but my git skills are not there! Sorry.

**Comment by Lochnair** [comment]
I've added binaries for the UniFi models with the latest snapshot. Until they catch up with EdgeOS, I'll maintain them separately.
