### ISSUE TITLE
Build on ER-X (mipsel)

### ISSUE THREAD

**Issue by foo4223** [Lochnair/vyatta-wireguard#5]
I'm trying to build WireGuard for the ER-X (which could be an interesting platform due to the higher clockspeed), and the kernel module build fails with 
```
Imake -C /lib/modules/3.10.14-UBNT/build M=/root/WireGuard/src modules
/root/WireGuard/src/Kbuild:34: "PEFORMANCE WARNING: WireGuard has enormous speed benefits when using CONFIG_PADATA on SMP systems. Please enable CONFIG_PADATA in your kernel configuration. See https://www.wireguard.io/install/#kernel-requirements for more info."
  CC [M]  /root/WireGuard/src/noise.o
In file included from <command-line>:0:0:
/root/WireGuard/src/compat/compat.h:13:2: warning: #warning "WireGuard support for kernels < 4.1 should work but is slightly experimental." [-Wcpp]
In file included from /root/WireGuard/src/noise.c:15:0:
include/crypto/algapi.h:401:19: error: redefinition of ‘crypto_memneq’
/root/WireGuard/src/compat/compat.h:190:19: note: previous definition of ‘crypto_memneq’ was here
make[2]: *** [/root/WireGuard/src/noise.o] Error 1
make[1]: *** [_module_/root/WireGuard/src] Error 2
make[1]: Leaving directory `/root/kernel'
make: *** [module] Error 2
```
I tried building according to your instructions (with the mipsel compiler) and with my method in a mipsel-qemu lauched via proot on the original rw-mounted squashfs. Please note that I didn't extract the cavm-executive packages,since they are missing in the GPL-archive as this is a mediatek and not an octeon platform.

**Comment by Lochnair** [comment]
I assume you've been reading the instructions on my website? Yeah, those are waaay outdated, and I'm using a different method for kernel compilation these days. 

I've forgotten about it, but I'll try to write up a new post with updated instructions in a couple of days.

I'll post here how I'm building the WireGuard binaries in a few.

**Comment by Lochnair** [comment]
@foo4223 I forgot to ask in my first post, but I'm guessing you haven't seen my post in the WireGuard release thread on the UBNT forum? I posted binaries for the ER-X there yesterday, and based on feedback, they seem to work.

**Comment by Lochnair** [comment]
Anyhoo, I'm using Docker images for cross-compiling to keep my system clean. So you can look at [this Dockerfile](https://github.com/Lochnair/docker-erx-kernel-dev/blob/master/Dockerfile) for a toolchain for kernel compilation for the ER-X, and [this](https://github.com/Lochnair/docker-mipsel-musl-dev/blob/master/Dockerfile) for setting up a musl toolchain for MIPSel. You'd also need to cross-compile libmnl before compiling wg(8), look [here](https://github.com/Lochnair/docker-mipsel-wireguard/blob/master/Dockerfile) for that.

When you've got all this setup make sure to compile the wg(8) utility like this:
```bash
git clone https://git.zx2c4.com/WireGuard
CC="mipsel-linux-musl-gcc" LDLIBS="-static -lmnl" make -C WireGuard/src/tools -j $(nproc)
```
We need to statically link the wg(8) utility to libmnl and musl because the glibc version on the Wheezy-based EdgeOS is ancient.

Compiling the kernel module is simple enough:
```
make ARCH=mips CROSS_COMPILE=mipsel-linux-gnu- -C ./kernel modules
make ARCH=mips CROSS_COMPILE=mipsel-linux-gnu- KERNELDIR=./kernel -C WireGuard/src module
```

**Comment by Lochnair** [comment]
@foo4223 I updated the latest release with a .deb file for the ER-X (the Ralink one). Please give it a try and see how it works for you.

**Comment by foo4223** [comment]
I could reproduce the build process and the .deb works nicely as well.
Thanks a lot!
